detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: true
    accept:
      - "/V[0-9]/"
  TooManyStatements:
    enabled: true
    max_statements: 20

exclude_paths:
  - db/migrate
